### PR TITLE
feat(PrivateRegistry): SRE-937 add private registry handling script & update release workflow

### PR DESCRIPTION
**Pull request by dawid-manikowski**
# SRE-937

## Add script which takes care of all the ops described [here](https://developer.hashicorp.com/terraform/cloud-docs/registry/publish-providers) for private provider publishing:
- create provider in TFC if not exist
- uploads GPG used to sign binaries if not exist
- creates provider version if not exist
- creates os/arch release package combinations if not exist
- uploads provider binaries if not uploaded

## Modify release workflow to use new script and push provider updates to our private registry

# Notes
I've added following GHA secrets:
- gpg public key
- tfc team token

### CODE REVIEW

**Comment by benscholler-ciq** [comment]
Should we create a way to delete the private registry in this script in case it needs to be removed in the future?

**Comment by dawid-manikowski** [comment]
Sure, I can add deletion. However it's not going to be used that often I think :D

**Comment by benscholler-ciq** [comment]
> Sure, I can add deletion. However it's not going to be used that often I think :D

In this case yeah. Having setup and tear down might be nice if we reuse this script for other repos in the future. Destroy would be good for testing out the functionality. I'll approve and leave it up to you.

**Review by benscholler-ciq — APPROVED** [review]

**Comment by dawid-manikowski** [comment]
Thank you, I will merge it so I can move forward with table split out and deal with the improvements during my next OKR

**Pull request merged**
